//------------------------------------------------------
// THIS FILE IS AUTOGENERATED
// DO NOT APPLY MANUAL MODIFICATIONS IN THIS FILE!
//------------------------------------------------------

const sqlite3 = require("sqlite3").verbose();
const filepath = "./db/main.sqlite";


// get by id
async function getById(id, callback) {
    const db = new sqlite3.Database(filepath, (error) => {
        if (error) {return console.log(error.message);}
        db.serialize(() => {
            let result = {};
            db.each(`SELECT * FROM employees WHERE id = ?`, [id], (error, row) => {
                if (error) {return console.log(error);}
                let recordToReturn = 
				{
id: row.id,					firstName: row.firstName,
					lastName: row.lastName,
					email1: row.email1,
					phone1: row.phone1,
				}                
                result = recordToReturn;
            },
            function() {
                callback(null, result);
            });
        });
    });
}


// list all
async function listAll(callback) {
    const db = new sqlite3.Database(filepath, (error) => {
        if (error) {return console.error(error.message);}
        db.serialize(() => {
            let result = [];
            db.each(`SELECT * FROM employees`, (error, row) => {
                if (error) {return console.log(error);}
                let newRecord = 
				{
id: row.id,					firstName: row.firstName,
					lastName: row.lastName,
					email1: row.email1,
					phone1: row.phone1,
				}                
                result.push(newRecord);
            },
            function() {
                callback(null, result);
            });
        });
    });
}


// save
async function save(params, callback) {
    const db = new sqlite3.Database(filepath, (error) => {
        if (error) {return console.error(error.message);}
        if (params.id > 0) {
            db.serialize(() => {
                db.prepare(`UPDATE employees SET firstName=?,lastName=?,email1=?,phone1=? WHERE id=?`, [params.firstName,params.lastName,params.email1,params.phone1,params.id]).run(
                    err => {
                        if (err != null) { db.close(); console.log(err.message) };
                    }
                    ).finalize(err => {
                        if (err != null) { db.close(); console.log(err.message) };
                    });
                db.close();
                callback(null, "ok");
            });
        }
        else
        {
            db.serialize(() => {
                db.prepare(`INSERT INTO employees (firstName,lastName,email1,phone1) VALUES (?,?,?,?)`, [params.firstName,params.lastName,params.email1,params.phone1]).run(
                    err => {
                        if (err != null) { db.close(); console.log(err.message) };
                    }
                    ).finalize(err => {
                        if (err != null) { db.close(); console.log(err.message) };
                    });
                db.close();
                callback(null, "ok");
            });            
        }
    });
}


module.exports = { getById, listAll, save }