//------------------------------------------------------
// THIS FILE IS AUTOGENERATED
// DO NOT APPLY MANUAL MODIFICATIONS IN THIS FILE!
//------------------------------------------------------

const sqlite3 = require("sqlite3").verbose();
const uuid = require('uuid');
const filepath = "./db/main.sqlite";
const sharedDBMethods = require('../../db/sharedDBFunctions.js');

async function getIdByGuid(guid, callback) {
    console.log("employeesProvider->getIdByGuid called with guid " + guid);
    const db = new sqlite3.Database(sharedDBMethods.returnDBPath(), (error) => {
        if (error) {return console.log(error.message);}
        db.serialize(() => {
            let result = -1;
            db.get(`SELECT id FROM employees WHERE guid=? LIMIT 1`, [guid], (error, row) => {
                console.log("employeesProvider->getIdByGuid returned row obj " + JSON.stringify(row));
                console.log("employeesProvider->getIdByGuid sql Error:" + error);
                result = row.id;
                console.log("employeesProvider->getIdByGuid this is the result: " + result);
                callback(null, result);
            });
        });
    });
}

async function getByGuid(params, callback) {
    const db = new sqlite3.Database(sharedDBMethods.returnDBPath(), (error) => {
        if (error) {return console.log(error.message);}
        db.serialize(() => {
            let result = {};
            console.log("employeesProvider->getByGuid Started with params: " + JSON.stringify(params));
            db.each(`SELECT * FROM employees WHERE guid=? AND isDeleted=0`, [params.guid,], (error, row) => {
                if (error) {return console.log(error);}
                let recordToReturn = 
				{
					guid: row.guid,
					email: row.email,
				}                
                result = recordToReturn;
            },
            function() {
                console.log("employeesProvider->getByGuid Finished (callback)");
                console.log("employeesProvider->getByGuid this is the result: " + JSON.stringify(result));
                callback(null, result);
            });
        });
    });
}

async function listAll(params, callback) {
    const db = new sqlite3.Database(sharedDBMethods.returnDBPath(), (error) => {
        if (error) {return console.log(error.message);}
        db.serialize(() => {
            let result = [];
            console.log("employeesProvider->listAll Started with params: " + JSON.stringify(params));
            db.each(`SELECT * FROM employees `, [], (error, row) => {
                if (error) {return console.log(error);}
                let recordToReturn = 
				{
					id: row.id,
					guid: row.guid,
					email: row.email,
					isDeleted: row.isDeleted,
				}                
                result.push(recordToReturn);
            },
            function() {
                console.log("employeesProvider->listAll Finished (callback)");
                console.log("employeesProvider->listAll this is the result: " + JSON.stringify(result));
                callback(null, result);
            });
        });
    });
}

// save
async function save(params, callback) {
    console.log("employeesProvider->save Started: " + JSON.stringify(params));
    const db = new sqlite3.Database(sharedDBMethods.returnDBPath(), (error) => {
        if (error) {return console.error(error.message);}
        if (params.id > 0) {
            db.serialize(() => {
                console.log("employeesProvider->save(update) Started");
                db.prepare(`UPDATE employees SET email=? WHERE id=?`, [params.email,params.id]).run(
                    err => {
                        if (err != null) { db.close(); console.log(err.message) };
                    }
                    ).finalize(err => {
                        if (err != null) { db.close(); console.log(err.message) };
                    });
                db.close();
                console.log("employeesProvider->save(update) Finished");
                callback(null, "ok");
            });
        }
        else
        {
            db.serialize(() => {
                console.log("employeesProvider->save(insert) Started");
                const uniqueUUID = uuid.v4();
                console.log("employeesProvider->save Generated guid for new record: " + uniqueUUID);
                db.prepare(`INSERT INTO employees (email,guid,isDeleted) VALUES (?,?,?)`, [params.email,uniqueUUID,0]).run(
                    err => {
                        if (err != null) { db.close(); console.log(err.message) };
                    }
                    ).finalize(err => {
                        if (err != null) { db.close(); console.log(err.message) };
                    });
                db.close();
                console.log("employeesProvider->save(insert) Finished");
                callback(null, "ok");
            });            
        }
    });
}

// logic delete
async function deleteLogic(params, callback) {
    console.log("employeesProvider->deleteLogic Started: " + JSON.stringify(params));
    const db = new sqlite3.Database(sharedDBMethods.returnDBPath(), (error) => {
        if (error) {return console.error(error.message);}
        if (params.id > 0) {
            db.serialize(() => {
                console.log("employeesProvider->deleteLogic(logic delete) Started");
                db.prepare(`UPDATE employees SET isDeleted=1 WHERE id=?`, [params.id]).run(
                    err => {
                        if (err != null) { db.close(); console.log(err.message) };
                    }
                    ).finalize(err => {
                        if (err != null) { db.close(); console.log(err.message) };
                    });
                db.close();
                console.log("employeesProvider->deleteLogic(logic delete) Finished");
                callback(null, "ok");
            });
        }
    });
}



module.exports = { getIdByGuid,getByGuid,listAll,save,deleteLogic, }