version: "3.4"

services:
  lema-backend:
    image: lema-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      SERVER_ENV: dev
      LISTENING_PORT: 9001
    ports:
      - 9001:9001
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
